### ISSUE TITLE
Word wrap not working for mobile styles with the expandRowColumn type.

### ISSUE THREAD

**Issue by w3MediaLabs** [kartik-v/yii2-grid#289]
When using dummy content and the expandRowColumn type, on a desktop screen the word wrap works fine.

![Good...](https://cloud.githubusercontent.com/assets/7306696/7426179/8d37a6cc-ef8d-11e4-9907-54677a046542.png)

But when I expand the row on a mobile device, the content isn't wrapped and it makes the detail container crazy long.

![Bad...](https://cloud.githubusercontent.com/assets/7306696/7426195/b659b504-ef8d-11e4-9870-a6fa749dfd22.png)

Any ideas?

**Comment by kartik-v** [comment]
That is because your table width exceeds the screen width. The table column content for expanded row (colspan is set to full width).

You can wrap your content inside a div. Give the div a CSS style using media query if the device width is smaller - basically giving it a fixed width.

```html
<div class="expanded-content">
Your expand row content
</div>
````

Then set your CSS

```css
@media screen and (max-width: 767px) {
    .expanded-content {
          max-width: 600px;
         /* set word-wrap etc. */
    }
}
```
